# JVM
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod metadata
mod_id=czechcraft
mod_version=1.0.0
mod_group=cz.czechcraft
mod_name=CzechCraft

# Minecraft / loader / mappings
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5

# Fabric
fabric_api_version=0.102.1+1.21.1

# Java
java_version=21
