plugins {
    id "fabric-loom" version "1.7-SNAPSHOT"
}

loom {
    // common module: no fabric runs, just vanilla MC for compilation + tests.
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
    testImplementation "org.mockito:mockito-core:5.12.0"
    testImplementation "org.mockito:mockito-junit-jupiter:5.12.0"
}

processResources {
    inputs.property "version", project.version
}

jar {
    from(rootProject.file("LICENSE")) { rename { "${it}_${project.mod_id}" } }
}
